[features]
seeds = false
skip-lint = false
[programs.localnet]
clusters = "CLR2boxd8sn2XnPM5vfEsdhDiUcvCaCuBg3zSzffYMe4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./wallet1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
