[features]
seeds = false
skip-lint = false
[programs.localnet]
clusters = "46wr5XGHYSMmaV6SAsRNkegSdi8qN69eSrbUVpByxNZo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/admin1/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
